 [server]
enableCORS = false
port = 8502
headless = true
enableXsrfProtection = false



[theme]
primaryColor = "#6C5CE7"
backgroundColor = "#F8F9FA"  
secondaryBackgroundColor = "#EAF2F8"
textColor = "#2C3E50"





